name: RewardEmAll
main: com.undergroundminer.remdul.rewardemall.RewardEmAll
version: 2.0
authors: [remdul]
website: http://dev.bukkit.org/server-mods/RewardEmAll
description: Rewards For Every Player Online! Share the wealth.
commands:
  Rea:
    description: Reward Em' All!
    usage: /Rea help
softdepend: [Vault]
permissions:
    rea.*:
        description: Gives access to all RewardEmAll Commands
        children:
            rea.heal: true
            rea.feed: true
            rea.effect: true
            rea.xp: true
            rea.cookie: true
            rea.fireworks: true
            rea.help: true
            rea.item: true
            rea.pay: true
    rea.heal:
        description: Allows you to heal everyone
        default: op
    rea.feed:
        description: Allows you to feed everyone
        default: op
    rea.effect:
        description: Allows you to give players speed
        default: op
    rea.xp:
        description: Allows you to Give 1,000 xp to players
        default: op
    rea.cookie:
        description: Allows you to give every player a stack of cookies
        default: op
    rea.fireworks:
        description: Launches Fireworks above players heads!
        default: op
    rea.help:
        description: Help for the RewardEmAll Commands
        default: op
    rea.item:
        description: Gives everyone however many of an item you specify.
        default: op
    rea.pay:
        description: Gives everyone money, based on your currency.
        default: op